use mpicl;
DROP TABLE IF EXISTS Tracks;
DROP TABLE IF EXISTS Codes;
DROP TABLE IF EXISTS Telemetry;

CREATE TABLE Codes(
code  INT NOT NULL  PRIMARY KEY ,
name  VARCHAR(50) NOT NULL,
description TEXT
) ENGINE = INNODB DEFAULT CHARSET=utf8;

CREATE TABLE Tracks ( 
filename VARCHAR(50) NOT NULL,
typeRecord INT NOT NULL,
typeEvent INT NOT NULL,
time FLOAT NOT NULL,
prid INT NOT NULL,
pid INT NOT NULL,
numData INT NOT NULL,
data VARCHAR(200),
FOREIGN KEY (typeEvent) REFERENCES Codes(code)
ON UPDATE NO ACTION ON DELETE NO ACTION 
) ENGINE = INNODB DEFAULT CHARSET=utf8;


CREATE TABLE Telemetry(
username VARCHAR(50) NOT NULL,
timeRequest  DATETIME NOT NULL,
timeStart FLOAT NOT NULL,
timeEND  FLOAT NOT NULL
) ENGINE = INNODB DEFAULT CHARSET=utf8;


